training_pipeline_config:
  artifact_dir: artifacts 

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/HARSHALKUMRE/Main-Branching/main/adult.csv
  raw_data_dir: raw_data 
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 